### ISSUE TITLE
Its sad that in bull markwt token is not rising

### ISSUE THREAD

**Issue by UGISPRO** [deeper-chain/deeper-chain#422]
The qestion is, why all legit tokens rising in this BULL market noe, but why this project not? iS IT THE CASE THAT PROJECT OWNERS CASHING OUT?

**Comment by jerry-yu** [comment]
do not talk abount token price

**Comment by edwardgrubb3rd** [comment]
> The qestion is, why all legit tokens rising in this BULL market noe, but why this project not? iS IT THE CASE THAT PROJECT OWNERS CASHING OUT?


RRun a script on known developer accounts transfers and you'll get the answer to your question.
