### ISSUE TITLE
Blockchain file storage over Deeper chain

### ISSUE THREAD

**Issue by kernel1983** [deeper-chain/deeper-chain#96]
File storage is a fundamental application for web3. This proposal is to build the files storage system over the blockchain.
Users can spend DPR to store their files. Beyond that, more applications can be feasible with blockchain storage.

The miner and the market decide the storage price.
The blockchain will set up a storage contract. Compared to a smart contract, the storage contract requires periodic verification.

### Problem
On a permission-less storage network, the storage providers may play out-souring attacks, which is risky to the file storage safety. The periodic verification requires performing the Proof of Replication to ensure the miners spend dedicated storage resources for the file owner. The random information from the blockchain can be used as a challenge to the miners. The miner must respond to the challenge to convince the owner.

### Solution
Currently, we are working on designing the storage contract prototype. It will involve the new protocol and algorithm to prevent out-souring attacks. The verification protocol may require more zero-knowledge magic.

The storage contract will keep the information about the files to save on the blockchain. The files were encrypted before uploading to the decentralized storage system. The encrypted data is divided into small chunks. Next, the chunks will be replicated into the unique replication form. Finally, the verification would start once the contract is initialized.

The design is early in the draft, so we may change the design detail or break the task into small components. Since the periodic verification would consume more TPS, it depends on better blockchain performance to support our application.

**Comment by edwardgrubb3rd** [comment]
IPFS storage would be great. That being said, it would be great to have interoperability with the top array of crypto based decentralized storage such as Sia, FileCoin, etc. 

Attaching network storage shouldn't be a problem.. I've integrated the top dozen crypto HDD storage mining with other crypto related projects.

I'd be willing to consult or dedicate engineering time.

@edwardgrubb3rd
